name: build-freecad
on:
  workflow_dispatch:
  push:
    paths:
      - '01_CAD/src/**.py'
      - '.github/workflows/build-freecad.yml'
      - '03_Docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch FreeCAD 1.0.0 AppImage + SHA256 (SourceForge)
        run: |
          set -euo pipefail
          APPIMG="FreeCAD_1.0.0-conda-Linux-x86_64-py311.AppImage"
          SHAFILE="${APPIMG}-SHA256.txt"
          # -L folgt Redirects von SourceForge
          curl -L -o "${APPIMG}" "https://sourceforge.net/projects/freecad.mirror/files/1.0.0/${APPIMG}/download"
          curl -L -o "${SHAFILE}" "https://sourceforge.net/projects/freecad.mirror/files/1.0.0/${SHAFILE}/download"
          sha256sum -c <(sed -E "s#^([0-9a-f]+) .*#\1  ${APPIMG}#g" "${SHAFILE}")
          chmod +x "${APPIMG}"
          # Entpacken, damit FreeCADCmd sicher im PATH ist
          ./"${APPIMG}" --appimage-extract
          echo "${GITHUB_WORKSPACE}/squashfs-root/usr/bin" >> "$GITHUB_PATH"

      - name: Build FCStd and STEP (FreeCADCmd)
        run: |
          mkdir -p 01_CAD/build
          FreeCADCmd -c 01_CAD/src/build_tars_fcstd.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TARS_v0.2_FCStd_STEP
          path: |
            01_CAD/build/TARS_v0.2.FCStd
            01_CAD/build/TARS_v0.2.step
          if-no-files-found: error
